### PR TITLE
various fixes, request -> isomorphic-fetch

### PR DESCRIPTION
**Pull request by derhuerst**
This PR brings `alexarank` up to date. [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch#isomorphic-fetch-) is a lot more lightweight than `request`.

### CODE REVIEW

**Comment by derhuerst** [comment]
The build failed in a really weird way. Would you mind to rerun the build?

**Comment by fcambus** [comment]
I relaunched the Travis build, it fails with 0.10 and 0.12.

**Comment by fcambus** [comment]
Merged, thanks!

**Comment by derhuerst** [comment]
Remember to push a new release to npm. 😉

**Pull request merged**
